name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature-release'
  - title: 'ğŸ› Hotfixes'
    label: 'bug-release'
  - title: 'ETC'
    label: '*'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Uncategorized
  $CHANGES
  ### Bump setup.py version must be included here!
